#!/usr/bin/env bash

# Copyright © 2018-2019 JPCDI, JPartain89 and Justin Partain
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script is to take media files downloaded and finished from sonarr and
# make them mp4 and add in the correct metadata

exec 1> >(logger -s -t "$(basename "$0")") 2>&1

ssh jpartain89@192.168.0.15 "{

    TMP=$(mktemp)

    cat << EOF > "$TMP"
#!/usr/bin/env bash

osascript -e \"
    set filePath to \(POSIX file \"${sonarr_episodefile_path}\" as alias\)
    tell application \"Subler\"
        add to queue filePath
    end tell\"
EOF

    bash "$TMP" &&
    rm "$TMP"
    exit
    }"
