name: Lint

on:
  schedule:
    - cron: '45 5 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:

jobs:
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use an action for ShellCheck to avoid apt installs and speed up setup
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v1
        with:
          args: mkvnmp4

      # Install shfmt via go but cache Go build and module cache to speed repeated runs
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ runner.os }}-go
            ${{ env.GOFLAGS }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install shfmt (cached)
        run: |
          mkdir -p "$HOME/go/bin"
          GOBIN="$HOME/go/bin" go install mvdan.cc/sh/v3/cmd/shfmt@v3.6.3
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run shfmt (check)
        run: shfmt -d . || true
