name: Tests

on:
  schedule:
    - cron: '45 5 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pytest
        run: python -m pip install pytest
      - name: Run pytest
        run: pytest -q

  bats-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run bats
        run: |
          chmod +x tests/mkvnmp4.bats
          tests/mkvnmp4.bats

  macos-smoke:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify python script loads
        run: |
          python3 -c "import mkvnmp4; print('OK')"
